from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_CustomerReviewWindow(object):

    def submitReview(self): # TODO
        input = self.commentInput.toPlainText()
        rating = self.ratingInput.text()
        print(input,rating)

    def setupUi(self, customerReview):
        customerReview.setObjectName("customerReview")
        customerReview.resize(392, 448)
        self.centralwidget = QtWidgets.QWidget(customerReview)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.totalcostLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.totalcostLabel.setFont(font)
        self.totalcostLabel.setObjectName("totalcostLabel")
        self.horizontalLayout.addWidget(self.totalcostLabel)
        self.totalcostOutput = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.totalcostOutput.setFont(font)
        self.totalcostOutput.setText("")
        self.totalcostOutput.setObjectName("totalcostOutput")
        self.horizontalLayout.addWidget(self.totalcostOutput)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.ratingInput = QtWidgets.QLineEdit(self.centralwidget)
        self.ratingInput.setObjectName("ratingInput")
        self.gridLayout.addWidget(self.ratingInput, 2, 1, 1, 1)
        self.commentInput = QtWidgets.QTextEdit(self.centralwidget)
        self.commentInput.setObjectName("textEdit")
        self.gridLayout.addWidget(self.commentInput, 1, 0, 1, 2)
        self.ratingLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ratingLabel.setFont(font)
        self.ratingLabel.setObjectName("ratingLabel")
        self.gridLayout.addWidget(self.ratingLabel, 2, 0, 1, 1)
        self.reviewLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reviewLabel.setFont(font)
        self.reviewLabel.setObjectName("commentLabel")
        self.gridLayout.addWidget(self.reviewLabel, 0, 0, 1, 1)
        self.reviewButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.submitReview())   # TO ASSIGN CUSTOMER'S COMMENT AND RATING... TODO
        self.reviewButton.setObjectName("reviewButton")
        self.gridLayout.addWidget(self.reviewButton, 3, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.feedbackLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.feedbackLabel.setFont(font)
        self.feedbackLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.feedbackLabel.setText("")
        self.feedbackLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.feedbackLabel.setObjectName("feedbackLabel")
        self.gridLayout_2.addWidget(self.feedbackLabel, 2, 0, 1, 1)
        customerReview.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(customerReview)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 392, 21))
        self.menubar.setObjectName("menubar")
        customerReview.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(customerReview)
        self.statusbar.setObjectName("statusbar")
        customerReview.setStatusBar(self.statusbar)

        self.retranslateUi(customerReview)
        QtCore.QMetaObject.connectSlotsByName(customerReview)

    def retranslateUi(self, customerReview):
        _translate = QtCore.QCoreApplication.translate
        customerReview.setWindowTitle(_translate("customerReview", "MainWindow"))
        self.totalcostLabel.setText(_translate("customerReview", "Yolculuk Tutarı:"))
        self.ratingLabel.setText(_translate("customerReview", "Puan Ver(1-5):"))
        self.reviewLabel.setText(_translate("customerReview", "Yorum Yap:"))
        self.reviewButton.setText(_translate("customerReview", "Gönder"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    customer = QtWidgets.QMainWindow()
    ui = Ui_CustomerReviewWindow()
    ui.setupUi(customer)
    customer.show()
    sys.exit(app.exec_())